"""
tools/mail_sender.py

Send RTL verification summary email.
"""

import os
import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from dotenv import load_dotenv
from langchain.tools import tool

from state import verification_state

load_dotenv()


@tool
def send_email_report() -> str:
    """
    Send RTL verification summary email.
    """

    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")

    if not sender or not password or not receiver:
        return "Email configuration missing."

    rtl_analysis = verification_state.get(
        "rtl_analysis",
        {}
    )

    missing_edge_cases = verification_state.get(
        "missing_edge_cases",
        []
    )

    rtl_text = rtl_analysis.get(
        "analysis",
        "No RTL issues found."
    )

    edge_case_text = ""

    if missing_edge_cases:
        for case in missing_edge_cases:
            edge_case_text += f"- {case}\n"
    else:
        edge_case_text = "None"

   
    # Email Body
   

    body = f"""
RTL Verification Summary

====================================

RTL Issues
------------------------------------

{rtl_text}

====================================

Missing Edge Cases
------------------------------------

{edge_case_text}

====================================

Generated by RTL Verification Agent
"""

    message = MIMEMultipart()

    message["From"] = sender
    message["To"] = receiver
    message["Subject"] = "RTL Verification Summary"

    message.attach(
        MIMEText(body, "plain")
    )

    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )

        server.starttls()

        server.login(
            sender,
            password
        )

        server.sendmail(
            sender,
            receiver,
            message.as_string()
        )

        server.quit()

        return (
            f"Email sent successfully to "
            f"{receiver}"
        )

    except Exception as e:

        return f"Email send failed: {e}"