"""
tools/report.py

Generate final RTL Verification Report.
"""

from pathlib import Path

try:
    from langchain.tools import tool
except Exception:
    def tool(func):
        return func

from state import verification_state


@tool
def generate_report() -> str:
    """
    Generate final verification report.
    """

    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)

    report_file = reports_dir / "verification_report.md"

    # ------------------------------------------------
    # State Data
    # ------------------------------------------------

    module_info = verification_state.get(
        "module_info",
        {}
    )

    simulation_result = verification_state.get(
        "simulation_result",
        {}
    )

    log_analysis = verification_state.get(
        "log_analysis",
        {}
    )

    rtl_analysis = verification_state.get(
        "rtl_analysis",
        {}
    )

    tb_analysis = verification_state.get(
        "tb_analysis",
        {}
    )

    missing_edge_cases = verification_state.get(
        "missing_edge_cases",
        []
    )

    rtl_file = verification_state.get(
        "rtl_file",
        "Unknown"
    )

    tb_file = verification_state.get(
        "tb_file",
        "Unknown"
    )

    # ------------------------------------------------
    # Report
    # ------------------------------------------------

    report = f"""# RTL Verification Report

---

## Input Files

**RTL File**

`{rtl_file}`

**Testbench File**

`{tb_file}`

---

## RTL Information

### Module Name

{module_info.get("module_name", "Unknown")}

### Inputs

{module_info.get("inputs", [])}

### Outputs

{module_info.get("outputs", [])}

### Parameters

{module_info.get("parameters", [])}

---

## Simulation Summary

### Compile Status

{simulation_result.get("compile_status", "UNKNOWN")}

### Simulation Status

{simulation_result.get("simulation_status", "UNKNOWN")}

### Compile Log

{simulation_result.get("compile_log", "N/A")}

### Simulation Log

{simulation_result.get("simulation_log", "N/A")}

---

## Log Analysis

### Compile Errors

{log_analysis.get("compile_error_count", 0)}

### Compile Warnings

{log_analysis.get("compile_warning_count", 0)}

### Simulation Errors

{log_analysis.get("simulation_error_count", 0)}

### Simulation Warnings

{log_analysis.get("simulation_warning_count", 0)}

### Detected Issues

{log_analysis.get("detected_issues", [])}

---

## RTL Design Analysis

{rtl_analysis.get("analysis", "No RTL analysis available.")}

---

## Testbench Analysis

{tb_analysis.get("analysis", "No Testbench analysis available.")}

---

## Missing Edge Cases

"""

    if missing_edge_cases:

        for item in missing_edge_cases:
            report += f"- {item}\n"

    else:

        report += "No missing edge cases detected.\n"

    report += """

---

## Verification Conclusion

Review RTL issues,
testbench weaknesses,
and missing edge cases before signoff.

Generated by RTL Verification Agent.

"""

    # ------------------------------------------------
    # Save Report
    # ------------------------------------------------

    report_file.write_text(
        report,
        encoding="utf-8"
    )

    # ------------------------------------------------
    # Save State
    # ------------------------------------------------

    verification_state["final_report"] = report

    # ------------------------------------------------
    # Return Summary
    # ------------------------------------------------

    return f"""
Verification report generated successfully.

Report Path:
{report_file}

Module:
{module_info.get("module_name", "Unknown")}

Compile Status:
{simulation_result.get("compile_status", "UNKNOWN")}

Simulation Status:
{simulation_result.get("simulation_status", "UNKNOWN")}
""".strip()